services:
  db:
    image: postgres:16-alpine
    container_name: firmadigital_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: firmadigital
      POSTGRES_USER: firmauser
      POSTGRES_PASSWORD: firmapass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
