sonar.projectKey=SebasParra_FirmaDigital_ValidacionCriptografica
sonar.organization=sebasparra

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.sources=backend/app,frontend/src
sonar.exclusions=**/*.pdf,**/*.doc,**/*.docx,**/node_modules/**,**/venv/**,**/__pycache__/**,backend/tests/**
